### ISSUE TITLE
I dont have any idea on how to access the chart editor.

### ISSUE THREAD

**Issue by Sinning-dev** [swordcube/NovaEngine-Godot-FNF#16]
### Describe your problem here.

Yep, exacly what the title says.
I've mashed all the keys on my keyboard but I cant find the bind to open the chart editor

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, I didnt edit anything

**Comment by swordcube** [comment]
You have to download the source code (main branch) in order to use the charter, it was never put into a release build
This should be easy enough to do though:

Go to "Code", click on it
![image](https://github.com/user-attachments/assets/ad95cd26-299c-4019-9eca-dbc551602d3d)

Then click "Download ZIP"
![image](https://github.com/user-attachments/assets/fe64af1e-18ce-4582-975e-65fdb95713e5)

Then if you don't have the Godot Game Engine downloaded, do so here:
https://godotengine.org

Then extract the zip to any place you want, open Godot, drag the extracted folder into Godot, click on "Edit" on the right side, wait for it to import assets, then press F5 to start the game!

That's it, no compiling needed!
Let me know if you have any other issues, but for now i'll close this issue :p
